import React, { useEffect, useState } from 'react'
import { useDispatch, useSelector } from 'react-redux'
import { Link, useNavigate } from 'react-router-dom'
import { LogOut, Package, ShoppingCart, Save, UserRound } from 'lucide-react'
import { logoutUser, setUser } from '../store/authSlice'
import { authApi } from '../lib/api'
import { fetchMyOrders } from '../store/ordersSlice'
import { selectCartItems } from '../store/cartSlice'

export default function Profile() {
  const dispatch = useDispatch(); const navigate = useNavigate()
  const { user, initialized } = useSelector(s => s.auth)
  const orders = useSelector(s => s.orders.items)
  const cart = useSelector(selectCartItems)
  const [form, setForm] = useState({ firstName:'', lastName:'', phone:'' }); const [saving, setSaving] = useState(false); const [message, setMessage] = useState('')
  useEffect(() => { if (user) { setForm({ firstName:user.firstName || '', lastName:user.lastName || '', phone:user.phone || '' }); if (!orders.length) dispatch(fetchMyOrders()) } }, [user, dispatch])
  if (initialized && !user) return <section className="max-w-xl mx-auto px-5 py-20 text-center"><UserRound className="w-12 h-12 mx-auto text-[#4A69E2] mb-4"/><h1 className="text-3xl font-black">YOUR ACCOUNT</h1><p className="text-neutral-500 mt-3">Sign in to manage your profile, cart and orders.</p><Link to="/login" className="inline-block mt-6 rounded-full bg-[#232321] text-white px-6 py-3 font-bold">Sign in</Link></section>
  if (!user) return null
  const save = async e => { e.preventDefault(); setSaving(true); setMessage(''); try { const res = await authApi.updateMe(form); dispatch(setUser(res.data)); setMessage('Profile saved successfully.') } catch (err) { setMessage(err.message) } finally { setSaving(false) } }
  const signOut = async () => { await dispatch(logoutUser()); navigate('/') }
  return <section className="max-w-6xl mx-auto px-4 sm:px-6 py-10 sm:py-14"><div className="rounded-[28px] bg-[#232321] text-white p-7 sm:p-10 flex flex-wrap gap-5 justify-between items-center"><div><p className="text-[#FFA52F] text-xs font-bold tracking-[.18em]">MY KICKS ACCOUNT</p><h1 className="text-3xl sm:text-4xl font-black uppercase mt-2">Hi, {user.firstName}</h1><p className="text-white/65 mt-2">{user.email}</p></div><button onClick={signOut} className="rounded-full border border-white/30 px-5 py-2.5 font-bold text-sm hover:bg-white hover:text-[#232321] transition"><LogOut className="inline w-4 h-4 mr-2"/>Log out</button></div><div className="grid md:grid-cols-3 gap-5 mt-6"><Link to="/cart" className="bg-white rounded-2xl p-6 border border-black/5 hover:-translate-y-1 transition shadow-sm"><ShoppingCart className="text-[#4A69E2]"/><strong className="block text-2xl mt-4">{cart.length}</strong><span className="text-sm text-neutral-500">Distinct items in your cart</span></Link><Link to="/orders" className="bg-white rounded-2xl p-6 border border-black/5 hover:-translate-y-1 transition shadow-sm"><Package className="text-[#4A69E2]"/><strong className="block text-2xl mt-4">{orders.length}</strong><span className="text-sm text-neutral-500">Orders & tracking</span></Link><Link to="/products" className="bg-[#FFA52F] rounded-2xl p-6 hover:-translate-y-1 transition"><strong className="block text-xl mt-8">Continue shopping →</strong><span className="text-sm">Explore new drops</span></Link></div><div className="mt-6 bg-white rounded-3xl border border-black/5 p-6 sm:p-8 max-w-3xl"><h2 className="font-black text-xl uppercase">Personal details</h2><form onSubmit={save} className="grid sm:grid-cols-2 gap-4 mt-6"><label className="text-sm font-bold">First name<input required value={form.firstName} onChange={e=>setForm({...form,firstName:e.target.value})} className="mt-2 w-full rounded-xl border p-3 font-normal"/></label><label className="text-sm font-bold">Last name<input required value={form.lastName} onChange={e=>setForm({...form,lastName:e.target.value})} className="mt-2 w-full rounded-xl border p-3 font-normal"/></label><label className="text-sm font-bold sm:col-span-2">Email<input disabled value={user.email || ''} className="mt-2 w-full rounded-xl border p-3 bg-neutral-100 text-neutral-500 font-normal"/></label><label className="text-sm font-bold sm:col-span-2">Phone<input value={form.phone || ''} onChange={e=>setForm({...form,phone:e.target.value})} className="mt-2 w-full rounded-xl border p-3 font-normal"/></label><div className="sm:col-span-2 flex items-center gap-4"><button disabled={saving} className="rounded-full bg-[#4A69E2] text-white px-6 py-3 font-bold disabled:opacity-60"><Save className="inline w-4 h-4 mr-2"/>{saving ? 'Saving…' : 'Save changes'}</button>{message && <span className="text-sm text-neutral-600" role="status">{message}</span>}</div></form></div></section>
}
