import { NewProduct } from "./schema";

export const SEED_PRODUCTS: NewProduct[] = [
  // ==================== MEN'S SNEAKERS ====================
  {
    name: "Air Max Pulse",
    brand: "Nike",
    price: 149,
    originalPrice: 180,
    gender: "Men",
    category: "Sneakers",
    collection: "Air Max Collection",
    img: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80",
    isNewDrop: true,
    isFeatured: true,
    rating: "4.9",
    reviewsCount: 142,
    description: "Engineered for street resilience and ultimate responsive air cushioning.",
  },
  {
    name: "Retro High OG",
    brand: "Jordan",
    price: 180,
    gender: "Men",
    category: "Basketball",
    collection: "Icons & Classics",
    img: "https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=800&q=80",
    isNewDrop: true,
    isFeatured: true,
    rating: "5.0",
    reviewsCount: 310,
    description: "The timeless high-top silhouette that defined sneaker culture.",
  },
  {
    name: "Classic Leather",
    brand: "Reebok",
    price: 85,
    originalPrice: 110,
    gender: "Men",
    category: "Lifestyle",
    collection: "Sale — up to 40%",
    img: "https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?auto=format&fit=crop&w=800&q=80",
    isNewDrop: false,
    isFeatured: false,
    rating: "4.7",
    reviewsCount: 89,
    description: "Clean heritage styling with soft garment leather and plush EVA foam.",
  },
  {
    name: "Old Skool Retro",
    brand: "Vans",
    price: 75,
    gender: "Men",
    category: "Skateboarding",
    collection: "Icons & Classics",
    img: "https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?auto=format&fit=crop&w=800&q=80",
    isNewDrop: false,
    isFeatured: false,
    rating: "4.8",
    reviewsCount: 204,
    description: "The iconic skate shoe featuring the legendary sidestripe and waffle outsole.",
  },
  {
    name: "Ultraboost Light",
    brand: "Adidas",
    price: 190,
    gender: "Men",
    category: "Running",
    collection: "Best Sellers",
    img: "https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80",
    isNewDrop: true,
    isFeatured: false,
    rating: "4.9",
    reviewsCount: 165,
    description: "Our lightest BOOST ever, designed with incredible energy return for daily runs.",
  },
  {
    name: "Air Zoom GT Cut",
    brand: "Nike",
    price: 170,
    gender: "Men",
    category: "Basketball",
    collection: "New Arrivals",
    img: "https://images.unsplash.com/photo-1579338559194-a162d19bf842?auto=format&fit=crop&w=800&q=80",
    isNewDrop: true,
    isFeatured: false,
    rating: "4.8",
    reviewsCount: 54,
    description: "Built for quick cuts, stop-on-a-dime traction, and explosive speed on the hardwood.",
  },
  {
    name: "Air Max 97 OG",
    brand: "Nike",
    price: 175,
    gender: "Men",
    category: "Sneakers",
    collection: "Air Max Collection",
    img: "https://images.unsplash.com/photo-1552346154-21d32810aba3?auto=format&fit=crop&w=800&q=80",
    isNewDrop: false,
    isFeatured: true,
    rating: "4.9",
    reviewsCount: 412,
    description: "Inspired by Japanese bullet trains with full-length visible air cushioning.",
  },
  {
    name: "NB 550 Vintage",
    brand: "New Balance",
    price: 110,
    originalPrice: 140,
    gender: "Men",
    category: "Lifestyle",
    collection: "Sale — up to 40%",
    img: "https://images.unsplash.com/photo-1539185441755-769473a23570?auto=format&fit=crop&w=800&q=80",
    isNewDrop: false,
    isFeatured: false,
    rating: "4.6",
    reviewsCount: 93,
    description: "The retro hoop classic revived for everyday street aesthetics.",
  },
  {
    name: "Dunk Low Retro",
    brand: "Nike",
    price: 115,
    gender: "Men",
    category: "Sneakers",
    collection: "Best Sellers",
    img: "https://images.unsplash.com/photo-1607522370275-f14206abe5d3?auto=format&fit=crop&w=800&q=80",
    isNewDrop: false,
    isFeatured: true,
    rating: "4.8",
    reviewsCount: 520,
    description: "Crisp leather overlays and heritage color blocking for everyday wear.",
  },
  {
    name: "Pegasus Trail 4",
    brand: "Nike",
    price: 140,
    gender: "Men",
    category: "Running",
    collection: "New Arrivals",
    img: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80",
    isNewDrop: true,
    isFeatured: false,
    rating: "4.7",
    reviewsCount: 68,
    description: "All-terrain confidence with rugged traction and React foam cushioning.",
  },

  // ==================== WOMEN'S SNEAKERS ====================
  {
    name: "Court Vision Low",
    brand: "Nike",
    price: 95,
    originalPrice: 120,
    gender: "Women",
    category: "Sneakers",
    collection: "Retro Court Pack",
    img: "https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=800&q=80",
    isNewDrop: true,
    isFeatured: true,
    rating: "4.9",
    reviewsCount: 198,
    description: "Fastbreak retro style of 1980s basketball meets the fast-paced culture of today.",
  },
  {
    name: "Solar Glide 6",
    brand: "Adidas",
    price: 130,
    gender: "Women",
    category: "Running",
    collection: "Best Sellers",
    img: "https://images.unsplash.com/photo-1560769629-975ec94e6a86?auto=format&fit=crop&w=800&q=80",
    isNewDrop: true,
    isFeatured: true,
    rating: "4.8",
    reviewsCount: 154,
    description: "Daily distance runners with LEP 2.0 torque guidance and plush BOOST comfort.",
  },
  {
    name: "Street Runner V2",
    brand: "Puma",
    price: 110,
    gender: "Women",
    category: "Training & Gym",
    collection: "New Arrivals",
    img: "https://images.unsplash.com/photo-1608231387042-66d1773070a5?auto=format&fit=crop&w=800&q=80",
    isNewDrop: true,
    isFeatured: false,
    rating: "4.7",
    reviewsCount: 77,
    description: "Agile training silhouette with breathable mesh and stabilized heel counter.",
  },
  {
    name: "Blazer Mid 77",
    brand: "Nike",
    price: 105,
    gender: "Women",
    category: "Sneakers",
    collection: "Street Icons",
    img: "https://images.unsplash.com/photo-1491553895911-0055eca6402d?auto=format&fit=crop&w=800&q=80",
    isNewDrop: false,
    isFeatured: true,
    rating: "4.9",
    reviewsCount: 340,
    description: "Old-school basketball look that delivers timeless comfort and vintage flair.",
  },
  {
    name: "Samba OG White",
    brand: "Adidas",
    price: 100,
    gender: "Women",
    category: "Lifestyle",
    collection: "Street Icons",
    img: "https://images.unsplash.com/photo-1582588678413-dbf45f4823e9?auto=format&fit=crop&w=800&q=80",
    isNewDrop: false,
    isFeatured: true,
    rating: "5.0",
    reviewsCount: 610,
    description: "Born on the pitch, standing icon of street fashion with T-toe suede overlay.",
  },
  {
    name: "Metcon 9 Women",
    brand: "Nike",
    price: 150,
    originalPrice: 180,
    gender: "Women",
    category: "Training & Gym",
    collection: "Sale — up to 40%",
    img: "https://images.unsplash.com/photo-1515955656352-a1fa3ffcd111?auto=format&fit=crop&w=800&q=80",
    isNewDrop: false,
    isFeatured: false,
    rating: "4.8",
    reviewsCount: 112,
    description: "Wider Hyperlift plate and rubber rope wrap for intense gym and CrossFit workouts.",
  },
  {
    name: "Cloudfoam Slide Luxe",
    brand: "Adidas",
    price: 45,
    originalPrice: 60,
    gender: "Women",
    category: "Sandals & Slides",
    collection: "Sale — up to 40%",
    img: "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=800&q=80",
    isNewDrop: false,
    isFeatured: false,
    rating: "4.6",
    reviewsCount: 228,
    description: "Quick-dry bandage strap with pillowy Cloudfoam footbed for post-workout recovery.",
  },
  {
    name: "Air Force 1 Shadow",
    brand: "Nike",
    price: 135,
    gender: "Women",
    category: "Sneakers",
    collection: "Retro Court Pack",
    img: "https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=800&q=80",
    isNewDrop: true,
    isFeatured: false,
    rating: "4.9",
    reviewsCount: 285,
    description: "Playful twist on a classic hoop design featuring layered details and doubled branding.",
  },
  {
    name: "Vaporfly 3 Next%",
    brand: "Nike",
    price: 260,
    gender: "Women",
    category: "Running",
    collection: "New Arrivals",
    img: "https://images.unsplash.com/photo-1552346154-21d32810aba3?auto=format&fit=crop&w=800&q=80",
    isNewDrop: true,
    isFeatured: false,
    rating: "5.0",
    reviewsCount: 88,
    description: "Race-day speed machine with carbon-fiber Flyplate and high-stack ZoomX foam.",
  },
  {
    name: "Chuck 70 Vintage Canvas",
    brand: "Converse",
    price: 90,
    originalPrice: 115,
    gender: "Women",
    category: "Lifestyle",
    collection: "Sale — up to 40%",
    img: "https://images.unsplash.com/photo-1607522370275-f14206abe5d3?auto=format&fit=crop&w=800&q=80",
    isNewDrop: false,
    isFeatured: false,
    rating: "4.8",
    reviewsCount: 190,
    description: "Premium craftsmanship with heavier canvas, extra cushioning, and glossy midsole.",
  }
];
