/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'surface-container-high': '#e7e8e9',
        'inverse-primary': '#d0bcff',
        'on-tertiary-fixed-variant': '#3d4756',
        'on-background': '#191c1d',
        'surface-container-lowest': '#ffffff',
        surface: '#f8f9fa',
        'surface-container-low': '#f3f4f5',
        'on-secondary-fixed-variant': '#464651',
        'on-surface-variant': '#494454',
        'surface-bright': '#f8f9fa',
        'on-secondary-fixed': '#1b1b25',
        'primary-container': '#8455ef',
        'primary-fixed': '#e9ddff',
        'on-primary-container': '#fffbff',
        'tertiary-fixed': '#d9e3f6',
        error: '#ba1a1a',
        outline: '#7b7486',
        'inverse-surface': '#2e3132',
        secondary: '#5e5d69',
        'secondary-container': '#e1deed',
        'on-primary-fixed-variant': '#5516be',
        'primary-fixed-dim': '#d0bcff',
        'on-secondary-container': '#62616e',
        'tertiary-fixed-dim': '#bdc7d9',
        'on-tertiary': '#ffffff',
        'secondary-fixed': '#e3e1ef',
        'surface-container-highest': '#e1e3e4',
        'outline-variant': '#cbc3d7',
        'surface-container': '#edeeef',
        'on-surface': '#191c1d',
        'on-primary-fixed': '#23005c',
        'secondary-fixed-dim': '#c7c5d3',
        'inverse-on-surface': '#f0f1f2',
        'on-secondary': '#ffffff',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'surface-variant': '#e1e3e4',
        'on-tertiary-container': '#fdfcff',
        'surface-tint': '#6d3bd7',
        'on-tertiary-fixed': '#121c2a',
        'on-primary': '#ffffff',
        'error-container': '#ffdad6',
        'surface-dim': '#d9dadb',
        tertiary: '#525d6c',
        background: '#f8f9fa',
        primary: '#6b38d4',
        'tertiary-container': '#6b7586',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
      spacing: {
        lg: '24px',
        xl: '32px',
        base: '4px',
        'gutter-mobile': '12px',
        md: '16px',
        sm: '12px',
        'margin-mobile': '20px',
        xs: '8px',
        13: '3.25rem',
        18: '4.5rem',
      },
      fontFamily: {
        sans: ['Manrope', 'sans-serif'],
        'body-md': ['Manrope'],
        'headline-lg-mobile': ['Manrope'],
        'headline-lg': ['Manrope'],
        'label-sm': ['Manrope'],
        'headline-md': ['Manrope'],
        'body-lg': ['Manrope'],
        'label-lg': ['Manrope'],
        'display-lg': ['Manrope'],
      },
      fontSize: {
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-lg-mobile': [
          '22px',
          { lineHeight: '28px', fontWeight: '700' },
        ],
        'headline-lg': [
          '24px',
          { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '700' },
        ],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '600' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '500' }],
        'label-lg': ['14px', { lineHeight: '16px', fontWeight: '600' }],
        'display-lg': [
          '32px',
          { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' },
        ],
      },
      keyframes: {
        popIn: {
          '0%': { transform: 'scale(0.9)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        slideUpFade: {
          '0%': { transform: 'translateY(10px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
      },
      animation: {
        'pop-in': 'popIn 0.4s ease-out forwards',
        'slide-up': 'slideUpFade 0.4s ease-out forwards',
      },
    },
  },
  plugins: [],
};
